FROM nvcr.io/nvidia/tritonserver:24.06-py3

COPY ./model_repository_running/bpr_model/1/requirements.txt /models/bpr_model/1/requirements.txt

RUN pip install -r /models/bpr_model/1/requirements.txt

COPY ./model_repository_running/ /models

CMD ["tritonserver", "--model-repository=/models", "--model-control-mode=explicit"]