adapter:
  retrieval_threshold: 0.9
  storage_folder: /storage

  rabbit:
    RABBIT_URL: amqp://guest:guest@localhost:5672/
    INPUT_TOPIC: input
    OUTPUT_TOPIC: frontend_output
  
  kafka:
    KAFKA_URL: localhost:9092
    INPUT_TOPIC: input
    OUTPUT_TOPIC: frontend_output
  
  binary_onnx:
    input_names: ['input']
    input_shape: [[-1, 512]]
    input_dtype: ['FP32']
    output_names: ['output']
    url: 'localhost:8001'
    model_name: 'binary_onnx'
    model_version: '1'
    connect_type: 'grpc'
  
  multilabel_onnx:
    input_names: ['input']
    input_shape: [[-1, 512]]
    input_dtype: ['FP32']
    output_names: ['output']
    url: 'localhost:8001'
    model_name: 'multilabel_onnx'
    model_version: '1'
    connect_type: 'grpc'
  
  vit_onnx:
    input_names: ['input']
    input_shape: [[-1, 1, 240, 480, 480]]
    input_dtype: ['FP32']
    output_names: ['output']
    url: 'localhost:8001'
    model_name: 'vit_onnx'
    model_version: '1'
    connect_type: 'grpc'
  
  bpr:
    input_names: ['input', 'metadata']
    input_shape: [[-1, -1, -1, -1], [-1, 3]]
    input_dtype: ['INT16', 'FP32']
    output_names: ['output']
    url: 'localhost:8001'
    model_name: 'bpr_model'
    model_version: '1'
    connect_type: 'grpc'
  
  binary_threshold: 0.5

  deseases2thresholds:
    Medical material: 0.5
    Arterial wall calcification: 0.5
    Cardiomegaly: 0.5
    Pericardial effusion: 0.5
    Coronary artery wall calcification: 0.5
    Hiatal hernia: 0.5
    Lymphadenopathy: 0.5
    Emphysema: 0.5
    Atelectasis: 0.5
    Lung nodule: 0.5
    Lung opacity: 0.5
    Pulmonary fibrotic sequela: 0.5
    Pleural effusion: 0.5
    Mosaic attenuation pattern: 0.5
    Peribronchial thickening: 0.5
    Consolidation: 0.5
    Bronchiectasis: 0.5
    Interlobular septal thickening: 0.5
    COVID-19: 0.5
    Cancer: 0.5
  
  severity_order:
    - Cancer
    - COVID-19
    - Pulmonary fibrotic sequela
    - Pleural effusion
    - Pericardial effusion
    - Cardiomegaly
    - Consolidation
    - Emphysema
    - Bronchiectasis
    - Atelectasis
    - Lung nodule
    - Lung opacity
    - Mosaic attenuation pattern
    - Interlobular septal thickening
    - Peribronchial thickening
    - Lymphadenopathy
    - Arterial wall calcification
    - Coronary artery wall calcification
    - Hiatal hernia
    - Medical material


frontend:
  KAFKA_BOOTSTRAP_SERVERS: localhost:9092
  RABBIT_URL: amqp://guest:guest@localhost:5672/
  INPUT_TOPIC: 'frontend_output'
  OUTPUT_TOPIC: 'input'
  STORAGE_FOLDER: /storage

  deseases2thresholds:
    Medical material: 0.5
    Arterial wall calcification: 0.5
    Cardiomegaly: 0.5
    Pericardial effusion: 0.5
    Coronary artery wall calcification: 0.5
    Hiatal hernia: 0.5
    Lymphadenopathy: 0.5
    Emphysema: 0.5
    Atelectasis: 0.5
    Lung nodule: 0.5
    Lung opacity: 0.5
    Pulmonary fibrotic sequela: 0.5
    Pleural effusion: 0.5
    Mosaic attenuation pattern: 0.5
    Peribronchial thickening: 0.5
    Consolidation: 0.5
    Bronchiectasis: 0.5
    Interlobular septal thickening: 0.5
    COVID-19: 0.5
    Cancer: 0.5